version: '3'

services:
  redis:
    image: redis
    hostname: "redis"
    expose:
      - "6379"
    networks:
      - visit-counter

  counter:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
    networks:
      - visit-counter


networks:
  visit-counter:
    driver: bridge